name: Daily REPO Mod Check

on:
  schedule:
    # 每天北京时间上午10:00运行（UTC 02:00）
    - cron: '0 2 * * *'
  workflow_dispatch: # 允许手动触发

# 定义权限
permissions:
  contents: write # 允许写入仓库内容

jobs:
  check-mod-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整历史以便正确提交
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Clean npm cache
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
      
      - name: Setup .npmrc
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "strict-ssl=true" >> .npmrc
          echo "force=true" >> .npmrc
          echo "audit=false" >> .npmrc
          echo "fund=false" >> .npmrc
          
      - name: Install dependencies
        run: npm install --no-package-lock
      
      - name: Create directories if not exist
        run: |
          mkdir -p public/downloads
          mkdir -p public/mods
          
      - name: Run mod updater script
        run: node scripts/mod_updater_ci.js
      
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          # 添加文件
          git add config.json public/downloads/ public/mods/ -f
          
          # 检查是否有变更
          if git diff --staged --quiet; then
            echo "No mod updates found."
            exit 0
          fi
          
          # 提交和推送变更
          git commit -m "自动更新: 模组检查 $(date +'%Y-%m-%d')"
          git push
          
      # 新增：触发Vercel部署  
      - name: Trigger Vercel Deployment
        if: success()
        run: |
          # 使用curl触发Vercel部署webhook
          if [ -n "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}" ]; then
            echo "正在触发Vercel部署..."
            curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
          else
            echo "未配置Vercel部署Webhook URL，跳过触发部署"
            echo "请在GitHub仓库设置中添加名为VERCEL_DEPLOY_HOOK_URL的secret"
            echo "该URL可在Vercel项目设置的Git Integration > Deploy Hooks中创建"
          fi 