name: Daily REPO Mod Check

on:
  schedule:
    # 每天北京时间上午10:00运行（UTC 02:00）
    - cron: '0 2 * * *'
  workflow_dispatch: # 允许手动触发

# 定义权限
permissions:
  contents: write # 允许写入仓库内容

jobs:
  check-mod-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整历史以便正确提交
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Create directories if not exist
        run: |
          mkdir -p public/downloads
          mkdir -p public/mods
          
      - name: Run mod updater script
        run: node scripts/mod_updater_ci.js
      
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          # 添加文件
          git add config.json public/downloads/ public/mods/ -f
          
          # 检查是否有变更
          if git diff --staged --quiet; then
            echo "No mod updates found."
            exit 0
          fi
          
          # 提交和推送变更
          git commit -m "自动更新: 模组检查 $(date +'%Y-%m-%d')"
          git push 